# Generated by Django 4.2.5 on 2023-10-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('nacionalidad', models.CharField(max_length=40)),
                ('fechaNac', models.DateField()),
                ('fechaFallecimiento', models.DateField()),
                ('movimiento', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('obras', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=40)),
                ('anio', models.CharField(max_length=4)),
                ('ubicacion', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
            ],
        ),
    ]
