# Generated by Django 4.2.5 on 2023-10-16 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GaleriaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='obras',
        ),
        migrations.AddField(
            model_name='artista',
            name='biografia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='cita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='artistas/'),
        ),
        migrations.AddField(
            model_name='artista',
            name='obras',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='biografia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='cita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='galerias/'),
        ),
        migrations.AddField(
            model_name='obra',
            name='artista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GaleriaApp.artista'),
        ),
        migrations.AddField(
            model_name='obra',
            name='biografia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='cita',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='obras/'),
        ),
        migrations.AddField(
            model_name='obra',
            name='galeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GaleriaApp.galeria'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('artista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_artista', to='GaleriaApp.artista')),
                ('galeria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_galeria', to='GaleriaApp.galeria')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_obra', to='GaleriaApp.obra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
