# Generated by Django 4.2.5 on 2023-10-16 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaApp', '0002_remove_galeria_obras_artista_biografia_artista_cita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='obras',
        ),
    ]
