# Generated by Django 4.2.5 on 2023-10-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaApp', '0003_remove_artista_obras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='artistas'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='galerias'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='obras'),
        ),
    ]
