# Generated by Django 4.2.5 on 2023-10-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaApp', '0005_alter_comentario_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='artista',
            name='biografia',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='cita',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='movimiento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nacionalidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='biografia',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='cita',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='ubicacion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='obra',
            name='artista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='GaleriaApp.artista'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='biografia',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='cita',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='galeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='GaleriaApp.galeria'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='material',
            field=models.CharField(max_length=200),
        ),
    ]
