# Generated by Django 4.2.5 on 2023-10-19 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaApp', '0006_remove_obra_autor_remove_obra_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='GaleriaApp.artista'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='galeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='GaleriaApp.galeria'),
        ),
    ]
