# Generated by Django 4.2.5 on 2023-10-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaApp', '0007_alter_obra_artista_alter_obra_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='anio',
            field=models.IntegerField(max_length=4),
        ),
    ]
