# Generated by Django 4.2.5 on 2023-10-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaApp', '0008_alter_obra_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='anio',
            field=models.IntegerField(),
        ),
    ]
