# Generated by Django 4.2.5 on 2023-10-20 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaApp', '0009_alter_obra_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='autor_post',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='fecha_post',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
