# Generated by Django 4.2.5 on 2023-10-20 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GaleriaApp', '0010_artista_autor_post_artista_fecha_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='autor_post',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='fecha_post',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='obra',
            name='autor_post',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='fecha_post',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
